name: Build & Publish

permissions:
  contents: write
  id-token: write

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build & Publish
        uses: fathym/build-n-publish@v1
